### ISSUE TITLE
Display related telemetry ping in a sidebar

### ISSUE THREAD

**Issue by jvehent** [leplatrem/aboutremotesettings#14]

**Comment by Natim** [comment]
Can you elaborate on what you want here? Open the add-on in a sidebar rather than in a tab?

**Comment by jvehent** [comment]
The idea was brought up by @leplatrem during our discussion to show the telemetry calls that relate to firefox settings as a sidebar of the about:remotesettings page.

**Comment by Natim** [comment]
Oh right 👍
