### ISSUE TITLE
Firefox 57 will only accept webextensions

### ISSUE THREAD

**Issue by Natim** [leplatrem/aboutremotesettings#7]
As noted on https://wiki.mozilla.org/Blocklisting/Admin#Testing this add-on will probably stop working as per Firefox 57.

I am creating this issue to see with @rhelmer what are our alternatives regarding that.
- Should we plan on shipping the about page in moz-central?
- Should we make it a system add-on with privileges permissions?
- Can we make it an add-on signed by Mozilla to allow it to access this private API's?

If you have a plan, don't hesitate to comment on this issue.

**Comment by rhelmer** [comment]
@andymckay - this is a good example of a developer/debugging add-on that needs privileged access and probably should not ship with Firefox, but would be really useful to still allow somehow on release.

>    Should we plan on shipping the about page in moz-central?

This will definitely work.

>    Should we make it a system add-on with privileges permissions?

This would work but would need to ship along with Firefox, so it's basically like the above.

>    Can we make it an add-on signed by Mozilla to allow it to access this private API's?

This is what we do for system add-ons and likely things like Test Pilot so it'd be interesting to consider.

Another option I think we should consider is allowing about:debugging temporary add-on loading to load these - it requires user interaction so it's hard for malware to abuse, and it allows this sort of testing on release channel which can be very valuable.

**Comment by andymckay** [comment]
Who uses this add-on and what's it for? Can you just add this to Firefox instead?

**Comment by Natim** [comment]
QA and Firefox devs for the blocklists update project are using it. It could ship within Firefox but then it would not be available for previous version of Firefox which didn't ship with it.

**Comment by andymckay** [comment]
I think shipping this in Firefox makes the most sense if its of value, or exposing the APIs to WebExtensions.

**Comment by Natim** [comment]
Refs [Bug 1403088](https://bugzilla.mozilla.org/show_bug.cgi?id=1403088)
