### ISSUE TITLE
about:remotesettings does not work on current release (51.0.1)

### ISSUE THREAD

**Issue by rhelmer** [leplatrem/aboutremotesettings#8]
The manifest only claims support for 53.* and above. If I modify this to support 51.* it loads but all values are "N/A" and changing the "Environment" does not seem to have an effect.

If this is expected and WONTFIX under 53 that's fine, I would like to update https://wiki.mozilla.org/Blocklisting/Admin#Testing with the appropriate steps for QA

**Comment by Natim** [comment]
I don't remember when was this code (kinto client) added to firefox, but it seems that below 53 it is not supposed to work yet.
