### ISSUE TITLE
Add support for new remote settings

### ISSUE THREAD

**Issue by Natim** [leplatrem/aboutremotesettings#9]
- [fingerprinting-defenses](https://bugzilla.mozilla.org/show_bug.cgi?id=1336208)
- ~~[stylo-blocklist](https://bugzilla.mozilla.org/show_bug.cgi?id=1403077)~~

**Comment by leplatrem** [comment]
Stylo was abandonned and fingerprinting still not merged. Shouldn't we close that issue and re-open one when it reaches production?

**Comment by Natim** [comment]
I don't think we should close it for fingerprinting because it will eventually land.

**Comment by leplatrem** [comment]
yes and there will be the [preload collection](https://bugzilla.mozilla.org/show_bug.cgi?id=1429795) also.
